### ISSUE TITLE
sonLib fails to compile with 'make' on MacOS 10.6.6

### ISSUE THREAD

**Issue by dentearl** [benedictpaten/sonLib#1]
...
cd C && make all
cp inc/_.h ../lib/
gcc -std=c99 -O3 -g -Wall -Werror --pedantic -funroll-loops -lm    -I/usr/local/mysql/include -DHAVE_MYSQL=1  -I inc -I ../lib/ -c impl/_.c
impl/sonLibKVDatabase_TokyoCabinet.c:18:20: error: tcutil.h: No such file or directory
impl/sonLibKVDatabase_TokyoCabinet.c:19:19: error: tcbdb.h: No such file or directory
impl/sonLibKVDatabase_TokyoCabinet.c:31: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘**attribute**’ before ‘_’ token
impl/sonLibKVDatabase_TokyoCabinet.c: In function ‘destructDB’:
impl/sonLibKVDatabase_TokyoCabinet.c:46: error: ‘TCBDB’ undeclared (first use in this function)
impl/sonLibKVDatabase_TokyoCabinet.c:46: error: (Each undeclared identifier is reported only once
impl/sonLibKVDatabase_TokyoCabinet.c:46: error: for each function it appears in.)
impl/sonLibKVDatabase_TokyoCabinet.c:46: error: ‘dbImpl’ undeclared (first use in this function)
cc1: warnings being treated as errors
impl/sonLibKVDatabase_TokyoCabinet.c:48: warning: implicit declaration of function ‘tcbdbclose’
impl/sonLibKVDatabase_TokyoCabinet.c:49: warning: implicit declaration of function ‘tcbdberrmsg’
impl/sonLibKVDatabase_TokyoCabinet.c:49: warning: implicit declaration of function ‘tcbdbecode’
impl/sonLibKVDatabase_TokyoCabinet.c:51: warning: implicit declaration of function ‘tcbdbdel’
impl/sonLibKVDatabase_TokyoCabinet.c: At top level:
impl/sonLibKVDatabase_TokyoCabinet.c:66: error: expected ‘)’ before ‘_’ token
impl/sonLibKVDatabase_TokyoCabinet.c: In function ‘containsRecord’:
impl/sonLibKVDatabase_TokyoCabinet.c:71: warning: implicit declaration of function ‘recordExists’
impl/sonLibKVDatabase_TokyoCabinet.c: In function ‘insertRecord’:
impl/sonLibKVDatabase_TokyoCabinet.c:75: error: ‘TCBDB’ undeclared (first use in this function)
impl/sonLibKVDatabase_TokyoCabinet.c:75: error: ‘dbImpl’ undeclared (first use in this function)
impl/sonLibKVDatabase_TokyoCabinet.c:79: warning: implicit declaration of function ‘tcbdbput’
impl/sonLibKVDatabase_TokyoCabinet.c: In function ‘updateRecord’:
impl/sonLibKVDatabase_TokyoCabinet.c:85: error: ‘TCBDB’ undeclared (first use in this function)
impl/sonLibKVDatabase_TokyoCabinet.c:85: error: ‘dbImpl’ undeclared (first use in this function)
impl/sonLibKVDatabase_TokyoCabinet.c: In function ‘numberOfRecords’:
impl/sonLibKVDatabase_TokyoCabinet.c:95: error: ‘TCBDB’ undeclared (first use in this function)
impl/sonLibKVDatabase_TokyoCabinet.c:95: error: ‘dbImpl’ undeclared (first use in this function)
impl/sonLibKVDatabase_TokyoCabinet.c:96: warning: implicit declaration of function ‘tcbdbrnum’
impl/sonLibKVDatabase_TokyoCabinet.c: In function ‘getRecord2’:
impl/sonLibKVDatabase_TokyoCabinet.c:100: error: ‘TCBDB’ undeclared (first use in this function)
impl/sonLibKVDatabase_TokyoCabinet.c:100: error: ‘dbImpl’ undeclared (first use in this function)
impl/sonLibKVDatabase_TokyoCabinet.c:103: warning: implicit declaration of function ‘tcbdbget’
impl/sonLibKVDatabase_TokyoCabinet.c:103: warning: initialization makes pointer from integer without a cast
impl/sonLibKVDatabase_TokyoCabinet.c: In function ‘removeRecord’:
impl/sonLibKVDatabase_TokyoCabinet.c:131: error: ‘TCBDB’ undeclared (first use in this function)
impl/sonLibKVDatabase_TokyoCabinet.c:131: error: ‘dbImpl’ undeclared (first use in this function)
impl/sonLibKVDatabase_TokyoCabinet.c:132: warning: implicit declaration of function ‘tcbdbout’
impl/sonLibKVDatabase_TokyoCabinet.c: In function ‘startTransaction’:
impl/sonLibKVDatabase_TokyoCabinet.c:138: error: ‘TCBDB’ undeclared (first use in this function)
impl/sonLibKVDatabase_TokyoCabinet.c:138: error: ‘dbImpl’ undeclared (first use in this function)
impl/sonLibKVDatabase_TokyoCabinet.c:139: warning: implicit declaration of function ‘tcbdbtranbegin’
impl/sonLibKVDatabase_TokyoCabinet.c: In function ‘commitTransaction’:
impl/sonLibKVDatabase_TokyoCabinet.c:145: error: ‘TCBDB’ undeclared (first use in this function)
impl/sonLibKVDatabase_TokyoCabinet.c:145: error: ‘dbImpl’ undeclared (first use in this function)
impl/sonLibKVDatabase_TokyoCabinet.c:147: warning: implicit declaration of function ‘tcbdbtrancommit’
impl/sonLibKVDatabase_TokyoCabinet.c: In function ‘abortTransaction’:
impl/sonLibKVDatabase_TokyoCabinet.c:153: error: ‘TCBDB’ undeclared (first use in this function)
impl/sonLibKVDatabase_TokyoCabinet.c:153: error: ‘dbImpl’ undeclared (first use in this function)
impl/sonLibKVDatabase_TokyoCabinet.c:154: warning: implicit declaration of function ‘tcbdbtranabort’
impl/sonLibKVDatabase_TokyoCabinet.c: In function ‘stKVDatabase_initialise_tokyoCabinet’:
impl/sonLibKVDatabase_TokyoCabinet.c:162: warning: implicit declaration of function ‘constructDB’
impl/sonLibKVDatabase_TokyoCabinet.c:162: warning: assignment makes pointer from integer without a cast
make[1]: **\* [../lib/sonLib.a] Error 1
make: **\* [cP] Error 2
